### PR TITLE
Fix Aspect validation when creating new aspect

### LINKED ISSUE #2467: BUG: Creating 2 aspects with the same title, results in aspect creation dialog to infinite loading state
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/test2/explore
2. Authenticate with GA
3. Create an Crad callout
4. Create an Aspect
5. Create second aspect with same title - error is thrown (this is expected)
6. Click on plus '+' button to create aspect again - dialog is open and loading indicator is displayed

**Expected behavior**
Client to prevent the user entering a title that is equal to an existing title.

### PR DESCRIPTION
**Pull request by ccanos**
### Describe the background of your pull request

Resolves #2467 

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

File: src/domain/callout/creation-dialog/useCalloutCreation/useCalloutCreation.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export const useCalloutCreation = (initialOpened = false): CalloutCreationUtils
         fields: {
           callouts(existing = []) {
             const newCalloutRef = cache.writeFragment({
-              data: createCalloutOnCollaboration,
+              data: { aspects: [], canvases: [], ...createCalloutOnCollaboration },
```
Comment (hero101) [inline src/domain/callout/creation-dialog/useCalloutCreation/useCalloutCreation.ts:82]: You can select the aspects and canvases in the query and don't bother anymore.
So create a fragment and use it both in the query and the mutation if they don't diverge that much.

**Review by hero101 — CHANGES_REQUESTED** [review]

**Review by hero101 — APPROVED** [review]
