### PR TITLE
React 18 fixes

### LINKED ISSUE #7751: BUG: [Bucket] React-18 upgrade issues
**Describe the bug**
See the excel file for details. 
https://stichtingcherrytwist-my.sharepoint.com/:x:/g/personal/borislav_alkem_io/EZW_CIc2zDxDtUekF-7pA_wBJTKEfyfLiO60xIzgLyg-5w?e=A4C27Y

**Screenshots**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

### PR DESCRIPTION
**Pull request by ccanos**
#7751

https://stichtingcherrytwist-my.sharepoint.com/:x:/g/personal/borislav_alkem_io/EZW_CIc2zDxDtUekF-7pA_wBJTKEfyfLiO60xIzgLyg-5w?e=A4C27Y

## Summary by CodeRabbit

- **Bug Fixes**
  - Corrected typos in property names related to scene initialization for improved functionality in collaboration features.
  - Adjusted whiteboard settings to prevent an infinite loading spinner and enhance collaboration.
  - Refined admin challenge navigation for a smoother experience.
- **Style**
  - Updated the space creation dialog’s label alignment for a cleaner layout.
  - Optimized header navigation by removing unnecessary scroll controls.
- **Chores**
  - Updated spell checker configuration to recognize new terms.

### CODE REVIEW

File: src/domain/shared/components/PageHeader/HeaderNavigationTabs.tsx [hunk 1]
```diff
@@ -51,6 +51,9 @@ const StyledTabs = styled(Tabs)(({ theme }) => ({
     marginLeft: '30%',
     marginRight: '30%',
   },
+  '.MuiTabs-scrollButtons': {
```
Comment (bobbykolev) [inline src/domain/shared/components/PageHeader/HeaderNavigationTabs.tsx:54]: let's double check that we're not introducing regression on mobile

**Review by bobbykolev — APPROVED** [review]
