### PR TITLE
Patch release 11

### LINKED ISSUE #7749: BUG: innovation hubs open user dashboard, instead of innovation hub home page
**Describe the bug**

**To Reproduce**

1. Go to https://demo.alkem.io/home
2. My dashboard page is open, instead of the innovation hub

**Expected behavior**
Innovation hub home page opens.

### PR DESCRIPTION
**Pull request by ccanos**
- Fix innovation flow tagset not found when accessing from space to subspace clicking the sidebar navigation
- Fix Create Subspace button not visible on sidebar
- Fix #7749 InnovationHubs url showing the url dashboard url

### CODE REVIEW

File: src/domain/collaboration/InnovationFlow/InnovationFlowStates/useInnovationFlowStates.ts [hunk 1]
```diff
@@ -23,8 +23,8 @@ const useInnovationFlowStates = ({
   const innovationFlow = data?.lookup.collaboration?.innovationFlow;
 
   const currentInnovationFlowState = innovationFlow?.currentState.displayName;
-  const myPrivilleges = innovationFlow?.authorization?.myPrivileges;
-  const canEditInnovationFlow = myPrivilleges?.includes(AuthorizationPrivilege.Update);
+  const myPrivileges = innovationFlow?.authorization?.myPrivileges;
```
Comment (ccanos) [inline src/domain/collaboration/InnovationFlow/InnovationFlowStates/useInnovationFlowStates.ts:26]: just a typo

**Comment by ccanos** [comment]
closed to trigger license/cla
